# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Stefan Lewis
"""Interactive field-marking tool (OpenCV HighGUI).

    python -m waruka markfield input_video_short.mp4 --time 2.0

Mark the four field corners on the RAW panorama (it shows the whole field;
the calibrated ray model handles the de-warp mathematically). Then add
extra points along each sideline -- they pin the cross-field Z scale that
4 corners alone cannot constrain.

Corner order (prompted on screen), 'left/right' as seen from the camera:
    1 NEAR-LEFT   2 NEAR-RIGHT   3 FAR-RIGHT   4 FAR-LEFT
(near = the sideline closest to the camera).

After 4 corners are placed the tool builds a fast 4-corner DLT "validator"
homography and uses it to reproject every subsequent sideline click in real
time. Dots are coloured by how far the click sits from its target line:
    green  : |Z - target| < 1 m   (good)
    yellow :              < 5 m   (borderline)
    red    :             >= 5 m   (likely wrong line / wrong field)

Predicted near (blue) and far (magenta) sideline guide lines are also drawn
once corners are placed -- click near the matching coloured line.

Once the 4th corner is placed the tool drops into AUTO mode: every
subsequent click is auto-classified as near or far by projecting it
through the 4-corner DLT and picking whichever sideline (Z=0 vs Z=W)
the predicted ground Z is closer to. Press A or B to force near or far,
or T to return to AUTO. In AUTO mode right-click removes the nearest
mark across all groups (no need to switch to corner mode to fix a
corner).

Press F to fit. The fit minimises mark error in metres (corners + sideline
points). By default it applies:
  * MLE auto-balance: per-mark weight = 1/(local click-error amplification),
    so middle marks count more than extreme-longitude ones. Disable with
    --no-auto-balance.
  * near_trust = 3.0: the near sideline (closest to the camera, easiest to
    verify visually) is weighted 3x as much as the far sideline. Tune with
    --near-trust FLOAT.
Both settings persist in project.json.
"""

from __future__ import annotations

import time
from pathlib import Path

import cv2
import numpy as np

# Reuse the calibrate helpers for OS-cursor warping + virtual->screen
# conversion + screen size detection + magnifier window style tweaks
# + cursor swap. Keeps all Win32 fiddling in one place.
from .calibrate import (_move_os_cursor, _virtual_to_screen,
                         _get_os_cursor_pos,
                         _detect_screen_size, LOUPE_ZOOM,
                         LOUPE_RADIUS_SRC_PX,
                         MAGNIFIER_RADIUS_SRC_PX,
                         _set_window_topmost_clickthrough,
                         _revert_window_styles,
                         _swap_window_class_cursor_invisible,
                         _restore_window_class_cursor)

from .config import ProjectConfig
from .ground import (GroundModel, compute_mle_weights, refine_homography,
                     sideline_residual_m, solve_homography)

CORNER_PROMPTS = [
    "Click corner 1/4: NEAR-LEFT  (near sideline, left end)",
    "Click corner 2/4: NEAR-RIGHT (near sideline, right end)",
    "Click corner 3/4: FAR-RIGHT  (far sideline, right end)",
    "Click corner 4/4: FAR-LEFT   (far sideline, left end)",
]
HELP = [
    "A=NEAR  B=FAR  T=AUTO  click+drag mark=move  right-click=remove nearest",
    "F=refit  G=toggle guides  H=toggle fitbox  U=undo  R=remove BAD",
    "Arrows=nudge cursor 1 src px   Enter/Space=commit at cursor",
    "M=magnifier mode (loupe follows cursor)",
    ",/. = scrub +-1s   < > = scrub +-10s   C=clear  S=save  Q/ESC=quit",
]
# Hit-test radius (display pixels) for click-near-mark detection used by
# both drag and right-click-remove.
HIT_PX = 25

# How long after a programmatic SetCursorPos to swallow incoming
# MOUSEMOVE events (the synthetic one generated by the OS arrives
# within a few ms; 100ms is a generous window).
SETCURSOR_FILTER_S = 0.10

# OpenCV arrow key codes via cv2.waitKeyEx. Windows + Linux/X11 return
# different full-width codes; both sets are accepted so nudging works
# regardless of platform. (Duplicated from calibrate.py to keep the
# two interactive tools self-contained.)
ARROW_LEFT_CODES  = (2424832, 65361)
ARROW_UP_CODES    = (2490368, 65362)
ARROW_RIGHT_CODES = (2555904, 65363)
ARROW_DOWN_CODES  = (2621440, 65364)

# Colour-by-residual thresholds for sideline clicks (in metres):
GOOD_M = 1.0    # < this -> green
WARN_M = 5.0    # < this -> yellow; >= -> red (also = "BAD" for R / save print)

# BGR colours
CLR_GOOD = (0, 220, 0)
CLR_WARN = (0, 220, 220)
CLR_BAD = (0, 0, 230)
CLR_CORNER = (0, 0, 255)
CLR_NEAR_MODE = (255, 140, 0)   # bright blue/orange for NEAR mode + guide
CLR_FAR_MODE = (200, 0, 200)    # magenta for FAR mode + guide
CLR_CORNER_MODE = (0, 0, 255)
CLR_AUTO_MODE = (60, 200, 230)  # bright amber for AUTO mode banner
CLR_FIELD_OUTLINE = (0, 220, 255)


def _corners_xz(L: float, W: float) -> np.ndarray:
    h = L / 2.0
    return np.array([[-h, 0.0], [h, 0.0], [h, W], [-h, W]], float)


def _mode_color(mode: str):
    return {"near": CLR_NEAR_MODE, "far": CLR_FAR_MODE,
            "corner": CLR_CORNER_MODE,
            "auto": CLR_AUTO_MODE}.get(mode, (200, 200, 200))


def _reproject_zs(pano, H, pts_src):
    """Reproject (sx, sy) source-pano points through H, return Z values."""
    if H is None or not pts_src:
        return np.empty(0)
    pts = np.asarray(pts_src, float)
    rays = pano.src_to_direction(pts[:, 0], pts[:, 1])
    Hinv = np.linalg.inv(H)
    q = (Hinv @ rays.T).T
    return q[:, 1] / q[:, 2]


def _color_for_residual(z, target):
    e = abs(z - target)
    if e < GOOD_M:
        return CLR_GOOD
    if e < WARN_M:
        return CLR_WARN
    return CLR_BAD


def run_markfield(video: str, project_path: str, t_seconds: float = 2.0,
                  length_m: float | None = None, width_m: float | None = None,
                  cam_height_m: float | None = None,
                  corner_weights: list[float] | None = None,
                  auto_balance_marks: bool | None = None,
                  near_trust: float | None = None):
    pp = Path(project_path)
    if not pp.exists():
        raise SystemExit(f"{pp} not found - run `waruka calibrate` first")
    cfg = ProjectConfig.load(pp)
    cfg.source_video = video
    if length_m:
        cfg.field_length_m = length_m
    if width_m:
        cfg.field_width_m = width_m
    # CLI overrides to the opt-in refinement controls (off by default).
    if cam_height_m is not None:
        cfg.cam_height_m = cam_height_m
    if corner_weights is not None:
        cfg.corner_weights = list(corner_weights)
    if auto_balance_marks is not None:
        cfg.auto_balance_marks = bool(auto_balance_marks)
    if near_trust is not None:
        cfg.near_trust = float(near_trust)
    use_auto_balance = bool(cfg.auto_balance_marks)
    near_trust_factor = float(cfg.near_trust)
    L, W = cfg.field_length_m, cfg.field_width_m
    pano = cfg.pano

    # Keep VideoCapture open for the whole session so scrubbing is fast.
    cap = cv2.VideoCapture(video)
    fps = cap.get(cv2.CAP_PROP_FPS) or 20.0
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
    total_seconds = (total_frames / fps) if total_frames else 0.0
    # Resume at the previously-scrubbed time if available, otherwise
    # the CLI/argument time.
    t_now = [float(cfg.last_scrub_t)
             if cfg.last_scrub_t is not None else float(t_seconds)]

    def grab_frame_at(t):
        """Decode the frame nearest to time t seconds. Returns (frame, disp)."""
        if total_frames > 0:
            target = max(0, min(total_frames - 1, int(t * fps)))
        else:
            target = int(t * fps)
        cap.set(cv2.CAP_PROP_POS_FRAMES, target)
        ok_, fr = cap.read()
        if not ok_:
            return None, None
        return fr, cv2.resize(fr, (int(w * scale), int(h * scale)))

    # Probe the first frame to learn the resolution, then build the scale.
    cap.set(cv2.CAP_PROP_POS_FRAMES, max(0, int(t_now[0] * fps)))
    ok, frame = cap.read()
    if not ok:
        cap.release()
        raise RuntimeError(f"cannot read {video} at {t_now[0]}s")
    h, w = frame.shape[:2]
    scale = min(1.0, 1500.0 / w)
    frame_ref = [frame]
    disp0_ref = [cv2.resize(frame, (int(w * scale), int(h * scale)))]

    def scrub(delta_s):
        t_new = max(0.0, min(max(total_seconds - 1e-3, 0.0),
                             t_now[0] + delta_s))
        fr, dp = grab_frame_at(t_new)
        if fr is None:
            print(f"scrub failed at t={t_new:.2f}s")
            return
        t_now[0] = t_new
        frame_ref[0] = fr
        disp0_ref[0] = dp

    # Corners are slot-based (length 4, None = empty) so right-click and
    # drag preserve the geometric meaning of each slot index.
    _loaded = list(cfg.field_marks.get("corners", []))
    corners: list[tuple[float, float] | None] = [
        (tuple(c) if c is not None else None) for c in _loaded
    ]
    while len(corners) < 4:
        corners.append(None)
    corners = corners[:4]

    near: list[tuple[float, float]] = list(
        map(tuple, cfg.field_marks.get("near", [])))
    far: list[tuple[float, float]] = list(
        map(tuple, cfg.field_marks.get("far", [])))
    # Initial mode: auto when 4 corners are already placed (most common
    # case for an existing project); corner mode otherwise so the user
    # can finish marking corners first.
    mode = ["auto" if all(c is not None for c in corners) else "corner"]
    gm: list[GroundModel | None] = [None]    # user-visible (LSQ-refined)
    H_val: list[np.ndarray | None] = [None]  # validator (4-corner DLT)
    resid = [{}]
    mouse = [0, 0]
    # Virtual cursor in SOURCE-frame coords (floats). Decouples the click
    # / loupe / drag-target position from the OS mouse pos so the arrow-
    # key nudge survives clicking. Mouse moves overwrite it; arrow keys
    # nudge it by 1 source pixel; LBUTTONDOWN + Enter/Space both commit
    # at this position.
    cursor_src = [0.0, 0.0]
    # Magnifier mode (loupe centred on cursor, click-through, stays
    # on top of the main window). Toggle with M.
    magnifier_mode = [False]
    # Saved loupe ex-style so the topmost + WS_EX_TRANSPARENT flags can
    # be reverted when magnifier mode is turned off.
    loupe_saved_style: list = [None]
    # Saved class cursor for the markfield window. Swapped to
    # IDC_CROSS in magnifier mode so the OS cursor hotspot lines up
    # with the loupe's drawn crosshair (otherwise the arrow tip is at
    # the hotspot but the visual arrow body extends down-right,
    # giving the illusion of a misaligned cross).
    saved_class_cursor: list = [None]
    # Timestamp guard for the synthetic MOUSEMOVE that arrives after
    # our SetCursorPos warp -- see calibrate.py for the full reason.
    last_setcursor_t = [0.0]
    # Drag state: None when not dragging, otherwise (mode, idx).
    drag: list = [None]
    # Overlay visibility (G/H toggles, persisted in cfg).
    show_guides = [bool(cfg.show_guides)]
    show_fitbox = [bool(cfg.show_fitbox)]

    win, loupe = "waruka markfield", "loupe (zoom)"
    cv2.namedWindow(win, cv2.WINDOW_NORMAL)
    cv2.namedWindow(loupe, cv2.WINDOW_NORMAL)
    # Cached screen dimensions for the magnifier-mode positioning math.
    # Falls back to a safe default on non-Windows / tkinter-less envs.
    screen_w, screen_h = _detect_screen_size()

    def filled_corners():
        return [c for c in corners if c is not None]

    def first_empty_slot():
        for i, c in enumerate(corners):
            if c is None:
                return i
        return None

    def rebuild_validator():
        fc = filled_corners()
        if len(fc) == 4:
            c = np.array(fc, float)
            crays = pano.src_to_direction(c[:, 0], c[:, 1])
            H_val[0] = solve_homography(crays, _corners_xz(L, W))
        else:
            H_val[0] = None

    def find_hit(sx, sy, mark_list):
        """Return index of nearest mark within HIT_PX display pixels."""
        best_i, best_d = None, float("inf")
        for i, m in enumerate(mark_list):
            if m is None:
                continue
            d_disp = np.hypot(m[0] - sx, m[1] - sy) * scale
            if d_disp < best_d:
                best_d, best_i = d_disp, i
        return best_i if best_i is not None and best_d < HIT_PX else None

    def find_hit_any(sx, sy):
        """Find nearest mark across corners/near/far. Returns (group, idx) or None."""
        best = None  # (group, idx, d_disp)
        for grp, lst in [("corner", corners), ("near", near), ("far", far)]:
            for i, m in enumerate(lst):
                if m is None:
                    continue
                d_disp = np.hypot(m[0] - sx, m[1] - sy) * scale
                if best is None or d_disp < best[2]:
                    best = (grp, i, d_disp)
        if best is None or best[2] >= HIT_PX:
            return None
        return best[0], best[1]

    def auto_classify(sx, sy):
        """Project (sx, sy) through validator H, return 'near' or 'far'.
        Pick whichever sideline (Z=0 or Z=W) the predicted ground Z is
        closer to. Returns None if no validator (corners incomplete)."""
        if H_val[0] is None:
            return None
        z = float(_reproject_zs(pano, H_val[0], [(sx, sy)])[0])
        return "near" if abs(z - 0.0) < abs(z - float(W)) else "far"

    def click_diag(label, idx, sx, sy, target_z):
        if H_val[0] is None:
            print(f"  {label}[{idx}] sx={sx:.0f} sy={sy:.0f} (no validator H yet)")
            return
        z = float(_reproject_zs(pano, H_val[0], [(sx, sy)])[0])
        e = abs(z - target_z)
        tag = "GOOD" if e < GOOD_M else ("warn" if e < WARN_M else "BAD ")
        print(f"  {label}[{idx:2d}] sx={sx:6.0f} sy={sy:5.0f}  "
              f"Z={z:+7.2f}m  target={target_z:+5.1f}  err={e:5.2f}  {tag}")

    def remove_nearest_in_mode(sx, sy):
        if mode[0] == "auto":
            # Remove nearest mark across all groups.
            hit = find_hit_any(sx, sy)
            if hit is None:
                print(f"no mark within {HIT_PX} px of cursor")
                return
            grp, idx = hit
            if grp == "corner":
                removed = corners[idx]
                corners[idx] = None
                gm[0] = None
                rebuild_validator()
                print(f"removed corner C{idx+1} at sx={removed[0]:.0f} "
                      f"sy={removed[1]:.0f}")
                # Auto mode requires 4 corners; drop back to corner mode
                # so the user refills the slot.
                if any(c is None for c in corners):
                    mode[0] = "corner"
                    print("auto needs 4 corners; switched to CORNER mode")
            else:
                lst = near if grp == "near" else far
                removed = lst.pop(idx)
                print(f"removed {grp} point #{idx+1} at sx={removed[0]:.0f} "
                      f"sy={removed[1]:.0f}")
            return
        if mode[0] == "corner":
            hit = find_hit(sx, sy, corners)
            if hit is None:
                print(f"no corner within {HIT_PX} px of cursor")
                return
            removed = corners[hit]
            corners[hit] = None
            gm[0] = None
            rebuild_validator()
            print(f"removed corner C{hit+1} at sx={removed[0]:.0f} "
                  f"sy={removed[1]:.0f}; next corner-mode click refills "
                  f"the first empty slot")
            return
        lst = near if mode[0] == "near" else far
        if not lst:
            return
        hit = find_hit(sx, sy, lst)
        if hit is None:
            print(f"no {mode[0]} point within {HIT_PX} px of cursor")
            return
        removed = lst.pop(hit)
        print(f"removed {mode[0]} point #{hit+1} at sx={removed[0]:.0f} "
              f"sy={removed[1]:.0f}")

    def add_mark_at(sx: float, sy: float) -> None:
        """Append a new mark at (sx, sy) following the current mode.

        Factored out of on_mouse's LBUTTONDOWN path so that Enter/Space
        can commit at the virtual cursor without going through a
        synthetic click event."""
        if mode[0] == "corner":
            slot = first_empty_slot()
            if slot is None:
                print("all 4 corners are filled; right-click to remove "
                      "one or drag to move")
                return
            corners[slot] = (sx, sy)
            if first_empty_slot() is None:
                rebuild_validator()
                mode[0] = "auto"
                print("4 corners placed; validator H built. "
                      "Switched to AUTO mode (clicks auto-classified).")
        elif mode[0] == "near":
            near.append((sx, sy))
            click_diag("near", len(near), sx, sy, 0.0)
        elif mode[0] == "far":
            far.append((sx, sy))
            click_diag("far ", len(far), sx, sy, float(W))
        elif mode[0] == "auto":
            cls = auto_classify(sx, sy)
            if cls is None:
                print("auto mode needs all 4 corners placed first")
                return
            if cls == "near":
                near.append((sx, sy))
                click_diag("auto->near", len(near), sx, sy, 0.0)
            else:
                far.append((sx, sy))
                click_diag("auto->far ", len(far), sx, sy, float(W))

    def sync_os_cursor_to_virtual():
        """Warp the OS cursor to the virtual cursor's screen position.
        Called from arrow-nudge handlers so the OS mouse pointer
        visibly tracks the loupe crosshair. The MOUSEMOVE swallow in
        on_mouse handles the synthetic move that the OS fires in
        response."""
        screen = _virtual_to_screen(cursor_src, scale, w, h, win)
        if screen is None:
            return
        last_setcursor_t[0] = time.monotonic()
        _move_os_cursor(*screen)

    def position_magnifier_loupe():
        """Centre the loupe on the OS cursor every loop tick while
        magnifier mode is on. The loupe also stays on top of the
        main window, ignores clicks (events pass through to the
        markfield window underneath), is borderless and circular --
        the magnifier-mode style bundle is applied lazily on first
        call and reverted by the M handler when toggled off."""
        if not magnifier_mode[0]:
            return
        magnifier_side = MAGNIFIER_RADIUS_SRC_PX * 2 * LOUPE_ZOOM
        if loupe_saved_style[0] is None:
            try:
                cv2.resizeWindow(loupe, magnifier_side, magnifier_side)
            except cv2.error:
                pass
            _set_window_topmost_clickthrough(
                loupe, loupe_saved_style, size=magnifier_side)
        # Authoritative cursor position from Win32 -- bypasses the cv2
        # mouse-coords + getWindowImageRect round-trip which showed an
        # offset in practice. Fallback to the round-trip on non-Win32.
        pos = _get_os_cursor_pos()
        if pos is None:
            pos = _virtual_to_screen(cursor_src, scale, w, h, win)
        if pos is None:
            return
        sx_screen, sy_screen = pos
        lx = sx_screen - magnifier_side // 2
        ly = sy_screen - magnifier_side // 2
        try:
            cv2.moveWindow(loupe, lx, ly)
        except cv2.error:
            pass

    def on_mouse(ev, x, y, *_):
        # Keep mouse[] as the raw display-coord tracker (still used by
        # draw_loupe-edge cases / future overlays). Mouse moves are the
        # ONLY thing that drives cursor_src to follow the OS cursor;
        # everything else reads cursor_src so an arrow-nudge applied
        # right before clicking survives.
        mouse[0], mouse[1] = x, y
        if ev == cv2.EVENT_MOUSEMOVE:
            # Swallow the synthetic MOUSEMOVE that follows our own
            # SetCursorPos call after an arrow nudge. Without this,
            # the display->source rounding round-trip would discard
            # the 1-source-pixel precision the nudge gave us.
            if time.monotonic() - last_setcursor_t[0] < SETCURSOR_FILTER_S:
                return
            cursor_src[0] = x / scale
            cursor_src[1] = y / scale
        sx, sy = cursor_src[0], cursor_src[1]
        if ev == cv2.EVENT_LBUTTONDOWN:
            # 1) If clicking near an existing mark, start drag. In auto
            # mode hit-test across ALL groups; in single-group modes
            # restrict to that group so an auto-mode-style mark doesn't
            # get pulled by a near-by mark of a different kind.
            if mode[0] == "auto":
                hit = find_hit_any(sx, sy)
                if hit is not None:
                    drag[0] = hit  # already (group, idx)
                    return
            else:
                lst = corners if mode[0] == "corner" else (
                    near if mode[0] == "near" else far)
                hit = find_hit(sx, sy, lst)
                if hit is not None:
                    drag[0] = (mode[0], hit)
                    return
            # 2) Otherwise add a new mark at the virtual cursor.
            add_mark_at(sx, sy)
        elif ev == cv2.EVENT_MOUSEMOVE:
            if drag[0] is not None:
                m, idx = drag[0]
                lst = corners if m == "corner" else (
                    near if m == "near" else far)
                if 0 <= idx < len(lst) and lst[idx] is not None:
                    lst[idx] = (sx, sy)
                    if m == "corner":
                        rebuild_validator()
        elif ev == cv2.EVENT_LBUTTONUP:
            if drag[0] is not None:
                m, idx = drag[0]
                lst = corners if m == "corner" else (
                    near if m == "near" else far)
                if 0 <= idx < len(lst) and lst[idx] is not None:
                    x_, y_ = lst[idx]
                    print(f"moved {m}[{idx+1}] -> sx={x_:.0f} sy={y_:.0f}")
                drag[0] = None
        elif ev == cv2.EVENT_RBUTTONDOWN:
            remove_nearest_in_mode(sx, sy)

    cv2.setMouseCallback(win, on_mouse)

    def fit():
        fc = filled_corners()
        if len(fc) != 4:
            print("need exactly 4 corners first")
            return
        c = np.array(fc, float)
        crays = pano.src_to_direction(c[:, 0], c[:, 1])
        nrays = (pano.src_to_direction(np.array(near)[:, 0],
                                        np.array(near)[:, 1])
                 if near else None)
        frays = (pano.src_to_direction(np.array(far)[:, 0],
                                        np.array(far)[:, 1])
                 if far else None)
        if (near or far):
            # Manual per-corner weight override (opt-in, 2026-05-29).
            cw_arr = (None if cfg.corner_weights is None
                      else list(cfg.corner_weights))
            if cw_arr is not None and len(cw_arr) != len(fc):
                print(f"WARNING: cfg.corner_weights has length "
                      f"{len(cw_arr)} but there are {len(fc)} "
                      f"corner marks; ignoring corner_weights.")
                cw_arr = None
            # Auto MLE weights (added 2026-05-30): per-mark weight from
            # how much a 1-pixel click error shifts the projected ground
            # point at that mark's location. Marks at extreme longitudes
            # get downweighted; well-conditioned middle marks get
            # upweighted. Computed once from the validator (DLT) H so
            # weights stay fixed during the LSQ.
            nw_arr = fw_arr = None
            if use_auto_balance and H_val[0] is not None:
                near_px = (np.asarray(near, float).reshape(-1, 2)
                           if near else None)
                far_px = (np.asarray(far, float).reshape(-1, 2)
                          if far else None)
                corner_px = np.asarray(fc, float).reshape(-1, 2)
                w = compute_mle_weights(pano, H_val[0],
                                        corner_px=corner_px,
                                        near_px=near_px, far_px=far_px)
                # Auto-corner only takes effect if user did NOT pass a
                # manual corner_weights override.
                if cw_arr is None and "corner" in w:
                    cw_arr = list(w["corner"])
                nw_arr = w.get("near")
                fw_arr = w.get("far")
            # Near-sideline trust boost: the near sideline is closest to
            # the camera and easiest to verify visually, so the user
            # treats it as essentially ground truth. Apply on top of MLE
            # (or on top of uniform when auto-balance is off).
            if near_trust_factor != 1.0 and near:
                if nw_arr is None:
                    nw_arr = np.full(len(near), near_trust_factor, dtype=float)
                else:
                    nw_arr = np.asarray(nw_arr, float) * near_trust_factor
            H = refine_homography(
                crays, _corners_xz(L, W), nrays, frays, W=W,
                corner_weights=cw_arr,
                near_weights=nw_arr,
                far_weights=fw_arr,
                cam_height_m=cfg.cam_height_m)
            gm[0] = GroundModel(H=H.reshape(-1).tolist(),
                                field_length_m=L, field_width_m=W)
            extras = []
            if use_auto_balance:
                extras.append("auto-balance")
            if near_trust_factor != 1.0:
                extras.append(f"near_trust={near_trust_factor:g}")
            if cfg.corner_weights is not None:
                extras.append(f"cw={list(cfg.corner_weights)}")
            if cfg.cam_height_m is not None:
                extras.append(f"Y_cam={cfg.cam_height_m}")
            extras_str = ("  [" + ", ".join(extras) + "]") if extras else ""
            mode_lbl = (f"LSQ corners+{len(near)}near+{len(far)}far"
                        + extras_str)
        else:
            gm[0] = GroundModel.fit(crays, _corners_xz(L, W), L, W)
            mode_lbl = "4-corner DLT (no sidelines)"
        nz = (gm[0].ground_from_ray(nrays) if nrays is not None else [])
        fz = (gm[0].ground_from_ray(frays) if frays is not None else [])
        resid[0] = sideline_residual_m(gm[0], np.array(nz) if len(nz) else [],
                                       np.array(fz) if len(fz) else [])
        resid[0]["fit"] = mode_lbl
        print(f"\nfit OK ({mode_lbl})  residual: {resid[0]}")
        # Per-point Z table after the LSQ fit
        if len(nz):
            nz_arr = np.asarray(nz)
            print("  near points (target Z=0):")
            errs = np.abs(nz_arr[:, 1])
            worst = int(np.argmax(errs))
            for i, (X, Z) in enumerate(nz_arr):
                tag = ("  <-- WORST" if i == worst and errs[i] > WARN_M
                       else ("  BAD" if errs[i] >= WARN_M
                             else ("  warn" if errs[i] >= GOOD_M else "")))
                print(f"    near[{i+1:2d}]  X={X:+7.2f}  Z={Z:+7.2f}{tag}")
        if len(fz):
            fz_arr = np.asarray(fz)
            print(f"  far points (target Z={W:.1f}):")
            errs = np.abs(fz_arr[:, 1] - W)
            worst = int(np.argmax(errs))
            for i, (X, Z) in enumerate(fz_arr):
                tag = ("  <-- WORST" if i == worst and errs[i] > WARN_M
                       else ("  BAD" if errs[i] >= WARN_M
                             else ("  warn" if errs[i] >= GOOD_M else "")))
                print(f"    far [{i+1:2d}]  X={X:+7.2f}  Z={Z:+7.2f}{tag}")
        print()

    def remove_bad_in_mode():
        if H_val[0] is None or mode[0] not in ("near", "far"):
            return
        lst = near if mode[0] == "near" else far
        target = 0.0 if mode[0] == "near" else float(W)
        if not lst:
            return
        zs = _reproject_zs(pano, H_val[0], lst)
        keep = [p for p, z in zip(lst, zs) if abs(z - target) < WARN_M]
        dropped = len(lst) - len(keep)
        lst[:] = keep
        print(f"R: removed {dropped} BAD {mode[0]} point(s) "
              f"(|Z-target| >= {WARN_M} m)")

    def draw():
        img = disp0_ref[0].copy()
        H_img, W_img = img.shape[:2]

        # 1) Field outline from LSQ-refined gm (only after F). Hidden by H toggle.
        if gm[0] is not None and show_fitbox[0]:
            b = gm[0].boundary_xz(2.0)
            d = gm[0].ray_from_ground(b)
            px, py = pano.directions_to_src(d)
            poly = np.column_stack([px * scale, py * scale]).astype(np.int32)
            cv2.polylines(img, [poly], True, CLR_FIELD_OUTLINE, 2, cv2.LINE_AA)

        # 2) Validator-predicted guide lines. Hidden by G toggle.
        if H_val[0] is not None and show_guides[0]:
            gm_val = GroundModel(H=H_val[0].reshape(-1).tolist(),
                                  field_length_m=L, field_width_m=W)
            xs = np.linspace(-L / 2, L / 2, 80)
            for Z_line, color in [(0.0, CLR_NEAR_MODE),
                                   (float(W), CLR_FAR_MODE)]:
                pts_xz = np.column_stack([xs, np.full_like(xs, Z_line)])
                rays = gm_val.ray_from_ground(pts_xz)
                px, py = pano.directions_to_src(rays)
                poly = np.column_stack([px * scale, py * scale]).astype(np.int32)
                cv2.polylines(img, [poly], False, color, 1, cv2.LINE_AA)

        # 3) Corner markers (skip empty slots; show "C#" labels matching slots)
        for i, c in enumerate(corners):
            if c is None:
                continue
            x, y = c
            p = (int(x * scale), int(y * scale))
            cv2.circle(img, p, 6, CLR_CORNER, -1)
            cv2.putText(img, str(i + 1), (p[0] + 6, p[1] - 6),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, CLR_CORNER, 2)

        # 4) Sideline markers, coloured by validator-H residual
        near_zs = (_reproject_zs(pano, H_val[0], near)
                   if H_val[0] is not None else None)
        far_zs = (_reproject_zs(pano, H_val[0], far)
                  if H_val[0] is not None else None)
        n_ok = n_bad = f_ok = f_bad = 0
        for i, (x, y) in enumerate(near):
            if near_zs is not None:
                c = _color_for_residual(near_zs[i], 0.0)
                if abs(near_zs[i]) >= WARN_M:
                    n_bad += 1
                else:
                    n_ok += 1
            else:
                c = CLR_NEAR_MODE
            cv2.circle(img, (int(x * scale), int(y * scale)), 4, c, -1)
        for i, (x, y) in enumerate(far):
            if far_zs is not None:
                c = _color_for_residual(far_zs[i], float(W))
                if abs(far_zs[i] - W) >= WARN_M:
                    f_bad += 1
                else:
                    f_ok += 1
            else:
                c = CLR_FAR_MODE
            cv2.circle(img, (int(x * scale), int(y * scale)), 4, c, -1)

        # 5) Top-left status HUD
        slot = first_empty_slot()
        n_filled = sum(1 for c in corners if c is not None)
        if slot is not None and n_filled < 4:
            prompt = CORNER_PROMPTS[slot]
        else:
            n_summary = (f"near: {len(near)} ({n_ok} OK, {n_bad} BAD)"
                         if H_val[0] is not None else f"near: {len(near)}")
            f_summary = (f"far: {len(far)} ({f_ok} OK, {f_bad} BAD)"
                         if H_val[0] is not None else f"far: {len(far)}")
            resid_str = (str(resid[0]) if resid[0]
                         else "(press F to LSQ-refit)")
            prompt = (f"corners=4  {n_summary}  {f_summary}  {resid_str}")
        # Time and overlay-toggle indicators on a separate line.
        time_line = (f"t={t_now[0]:6.2f}s / {total_seconds:.1f}s   "
                     f"guides={'ON' if show_guides[0] else 'OFF'}   "
                     f"fitbox={'ON' if show_fitbox[0] else 'OFF'}")
        y0 = 20
        for t in [prompt, time_line, *HELP]:
            cv2.putText(img, t, (8, y0), cv2.FONT_HERSHEY_SIMPLEX, 0.55,
                        (0, 0, 0), 3, cv2.LINE_AA)
            cv2.putText(img, t, (8, y0), cv2.FONT_HERSHEY_SIMPLEX, 0.55,
                        (255, 255, 255), 1, cv2.LINE_AA)
            y0 += 24

        # 6) Big mode HUD banner at the bottom-centre
        mode_text = {
            "corner": f"MARKING: CORNERS  ({n_filled}/4)",
            "near":   "MARKING: NEAR SIDELINE  (target Z=0)",
            "far":    f"MARKING: FAR SIDELINE  (target Z={W:.0f})",
            "auto":   "MARKING: AUTO  (clicks classified near/far)",
        }[mode[0]]
        mc = _mode_color(mode[0])
        font, fs, ft = cv2.FONT_HERSHEY_SIMPLEX, 1.0, 2
        (tw, th), _ = cv2.getTextSize(mode_text, font, fs, ft)
        bx, by = (W_img - tw) // 2, H_img - 18
        pad = 10
        cv2.rectangle(img, (bx - pad, by - th - pad),
                      (bx + tw + pad, by + pad), mc, -1)
        cv2.putText(img, mode_text, (bx, by), font, fs,
                    (255, 255, 255), ft, cv2.LINE_AA)
        return img

    def draw_loupe():
        # Centre the loupe on the virtual cursor (which arrow-nudges
        # operate on), not the raw mouse position. Without this, a
        # nudge would adjust the click target but leave the loupe view
        # behind. In magnifier mode the crop radius shrinks so the
        # floating loupe stays compact rather than swamping the
        # markfield image.
        sx, sy = int(cursor_src[0]), int(cursor_src[1])
        r = (MAGNIFIER_RADIUS_SRC_PX
              if magnifier_mode[0] else LOUPE_RADIUS_SRC_PX)
        x0, y0 = max(0, sx - r), max(0, sy - r)
        crop = frame_ref[0][y0:sy + r, x0:sx + r]
        if crop.size == 0:
            return
        z = cv2.resize(crop,
                        (crop.shape[1] * LOUPE_ZOOM,
                         crop.shape[0] * LOUPE_ZOOM),
                        interpolation=cv2.INTER_NEAREST)
        cx, cy = (sx - x0) * LOUPE_ZOOM, (sy - y0) * LOUPE_ZOOM
        cv2.drawMarker(z, (cx, cy), _mode_color(mode[0]),
                       cv2.MARKER_CROSS, 24, 2)
        cv2.imshow(loupe, z)

    # Build validator at startup in case the project already has 4 corners.
    rebuild_validator()

    while True:
        cv2.imshow(win, draw())
        draw_loupe()
        position_magnifier_loupe()
        # waitKeyEx so arrow keys come through with their full
        # platform-specific code (waitKey masks to the low byte, which
        # truncates arrow codes to 0 on Windows).
        k_full = cv2.waitKeyEx(20)
        if k_full == -1:
            continue
        k = k_full & 0xFF

        # Arrow nudges: one source pixel per press. After updating
        # cursor_src, warp the OS cursor so the mouse pointer visibly
        # tracks the loupe crosshair. OS auto-repeat handles holds.
        if k_full in ARROW_LEFT_CODES:
            cursor_src[0] = max(0.0, cursor_src[0] - 1.0)
            sync_os_cursor_to_virtual()
            continue
        if k_full in ARROW_RIGHT_CODES:
            cursor_src[0] = min(float(w - 1), cursor_src[0] + 1.0)
            sync_os_cursor_to_virtual()
            continue
        if k_full in ARROW_UP_CODES:
            cursor_src[1] = max(0.0, cursor_src[1] - 1.0)
            sync_os_cursor_to_virtual()
            continue
        if k_full in ARROW_DOWN_CODES:
            cursor_src[1] = min(float(h - 1), cursor_src[1] + 1.0)
            sync_os_cursor_to_virtual()
            continue
        # Enter (13) or Space (32) commits a new mark at the virtual
        # cursor without a click. Useful after nudging precisely with
        # arrows -- clicking would jump the cursor back to the OS
        # mouse position.
        if k_full in (13, 32):
            add_mark_at(cursor_src[0], cursor_src[1])
            continue
        # M toggles magnifier mode: loupe centred on the OS cursor,
        # borderless + circular + click-through, stays on top of the
        # markfield window. The window class cursor swaps to a
        # centred crosshair so it aligns with the loupe's drawn cross.
        # When turned off, all magnifier-mode tweaks (cursor, styles,
        # loupe size) revert.
        if k == ord("m"):
            magnifier_mode[0] = not magnifier_mode[0]
            print(f"magnifier mode: "
                  f"{'ON (centred + borderless + circular + click-through, cross cursor)' if magnifier_mode[0] else 'OFF'}")
            if magnifier_mode[0]:
                # Hide the OS cursor so only the loupe's drawn
                # crosshair is visible -- sidesteps any visual offset
                # between the cursor's hotspot and its rendered shape.
                _swap_window_class_cursor_invisible(
                    win, saved_class_cursor)
            else:
                _restore_window_class_cursor(win, saved_class_cursor)
                _revert_window_styles(loupe, loupe_saved_style)
                normal_side = LOUPE_RADIUS_SRC_PX * 2 * LOUPE_ZOOM
                try:
                    cv2.resizeWindow(loupe, normal_side, normal_side)
                except cv2.error:
                    pass
            continue

        if k == 255 or k == 0:
            continue
        if k in (ord("q"), 27):
            break
        elif k == ord("a"):
            mode[0] = "near"
        elif k == ord("b"):
            mode[0] = "far"
        elif k == ord("t"):
            if all(c is not None for c in corners):
                mode[0] = "auto"
            else:
                print("auto mode needs all 4 corners placed first")
        elif k == ord("u"):
            if mode[0] == "near" and near:
                near.pop()
            elif mode[0] == "far" and far:
                far.pop()
            elif mode[0] == "auto":
                # No explicit order tracking; undo near→far→corner.
                if near:
                    near.pop()
                elif far:
                    far.pop()
                elif any(c is not None for c in corners):
                    for i in range(3, -1, -1):
                        if corners[i] is not None:
                            corners[i] = None
                            break
                    mode[0] = "corner"
                    gm[0] = None
                    rebuild_validator()
            elif any(c is not None for c in corners):
                # Set the highest-index filled corner to None.
                for i in range(3, -1, -1):
                    if corners[i] is not None:
                        corners[i] = None
                        break
                mode[0] = "corner"
                gm[0] = None
                rebuild_validator()
        elif k == ord("r"):
            remove_bad_in_mode()
        elif k == ord("c"):
            for i in range(4):
                corners[i] = None
            near.clear(); far.clear()
            mode[0] = "corner"; gm[0] = None; resid[0] = {}
            rebuild_validator()
        elif k == ord("f"):
            fit()
        elif k == ord("g"):
            show_guides[0] = not show_guides[0]
            cfg.show_guides = show_guides[0]
            print(f"guides: {'ON' if show_guides[0] else 'OFF'}")
        elif k == ord("h"):
            show_fitbox[0] = not show_fitbox[0]
            cfg.show_fitbox = show_fitbox[0]
            print(f"fitbox: {'ON' if show_fitbox[0] else 'OFF'}")
        elif k == ord(","):
            scrub(-1.0)
        elif k == ord("."):
            scrub(+1.0)
        elif k == ord("<"):
            scrub(-10.0)
        elif k == ord(">"):
            scrub(+10.0)
        elif k == ord("s"):
            # Auto-fit if marks changed since last fit, so we don't save a
            # stale homography.
            if all(c is not None for c in corners) and (
                    gm[0] is None or near or far):
                fit()
            cfg.field_marks = {
                "corners": [list(c) if c is not None else None
                            for c in corners],
                "near": [list(c) for c in near],
                "far": [list(c) for c in far],
            }
            cfg.field_polygon = [list(c) for c in corners if c is not None]
            cfg.last_scrub_t = float(t_now[0])
            if gm[0] is not None:
                cfg.homography = gm[0].H
            cfg.save(pp)
            # Final BAD-point summary on save
            if H_val[0] is not None:
                n_bad = int(np.sum(np.abs(_reproject_zs(pano, H_val[0], near))
                                    >= WARN_M)) if near else 0
                f_bad = int(np.sum(np.abs(_reproject_zs(pano, H_val[0], far)
                                          - W) >= WARN_M)) if far else 0
                bad_note = (f"  BAD: near={n_bad} far={f_bad}"
                            if (n_bad or f_bad) else "")
            else:
                bad_note = ""
            print(f"saved {pp}  near={len(near)} far={len(far)}{bad_note}  "
                  f"residual={resid[0]}")

    cap.release()
    cv2.destroyAllWindows()
